// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orderista.Models;

namespace Orderista.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190718064222_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Orderista.Models.Customer", b =>
                {
                    b.Property<int>("CuId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<int?>("Hostel");

                    b.Property<string>("Name");

                    b.Property<int>("Phone")
                        .HasMaxLength(11);

                    b.Property<int>("Room")
                        .HasMaxLength(3);

                    b.HasKey("CuId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Orderista.Models.Restaurant", b =>
                {
                    b.Property<int>("RuId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<int>("Phone");

                    b.HasKey("RuId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RuId = 1,
                            Name = "Jammin Java",
                            Phone = 0
                        },
                        new
                        {
                            RuId = 2,
                            Name = "Subway",
                            Phone = 0
                        },
                        new
                        {
                            RuId = 3,
                            Name = "Zakir Tikka",
                            Phone = 0
                        },
                        new
                        {
                            RuId = 4,
                            Name = "Chop Chop",
                            Phone = 0
                        },
                        new
                        {
                            RuId = 5,
                            Name = "Bombay Chowpatty",
                            Phone = 0
                        },
                        new
                        {
                            RuId = 6,
                            Name = "Juice Zone",
                            Phone = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
